### ISSUE TITLE
error with python 3.7

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/python-devtools#29]
```
Traceback (most recent call last):
  File "/home/samuel/code/email-forward/env/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 315, in _handle_client
    await method(arg)
  File "/home/samuel/code/email-forward/env/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 380, in smtp_NOOP
    status = await self._call_handler_hook('NOOP', arg)
  File "/home/samuel/code/email-forward/env/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 122, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
  File "./run.py", line 14, in handle_NOOP
    print('Message data:\n')
  File "/home/samuel/code/email-forward/env/lib/python3.7/site-packages/devtools/debug.py", line 112, in __call__
    d_out = self._process(args, kwargs, r'debug *\(')
  File "/home/samuel/code/email-forward/env/lib/python3.7/site-packages/devtools/debug.py", line 153, in _process
    func_ast, code_lines, lineno = self._parse_code(call_frame, func_regex, filename)
  File "/home/samuel/code/email-forward/env/lib/python3.7/site-packages/devtools/debug.py", line 223, in _parse_code
    func_ast = self._wrap_parse(code, filename)
  File "/home/samuel/code/email-forward/env/lib/python3.7/site-packages/devtools/debug.py", line 260, in _wrap_parse
    return ast.parse(code, filename=filename).body[0].body[0].value
AttributeError: 'Import' object has no attribute 'value'
```

**Comment by samuelcolvin** [comment]
duplicate of #21.
